# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjUyY2EwMjZjMzg4NGRkYjllNTJkNTcwZjQyNjQ5NjgyYTgzOWM4Y2RmMzhmZWE5YTNkMWYzZGY4NDU5MGI4ODk1NTU2YmZhMDkxMjM0MmI4YmY1NmI4YzJmOTgxY2NjNGQwNTM5ZDBhZWUyMDgwNTY1M2M5NDMzMzYwYjdmZGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
